version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: docker/user-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - JWT_SECRET=your_jwt_secret_here
      - APP_ENV=development
    depends_on:
      - mongo

  task-service:
    build:
      context: .
      dockerfile: docker/task-service/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - JWT_SECRET=your_jwt_secret_here
      - APP_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 