name: PR Test

on:
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      # Goのセットアップ時にcache: trueを指定
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version

      - name: Install Go dependencies
        run: |
          go install -v google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install -v google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          GOGC=off go mod download
          GOGC=off go mod tidy

      - name: Generate Proto files
        run: make proto

      - name: Update dependencies after proto generation
        run: GOGC=off go mod tidy

      - name: Run Tests
        run: make test
        env:
          MONGODB_URI: mongodb://localhost:27017
          JWT_SECRET_KEY: test-secret-key
